### ISSUE TITLE
Friend text off screen

### ISSUE THREAD

**Issue by Ag3ntunkn0wn** [Vicious-wow/XIV_Databar#1]
If the bar is set to be at the top of the screen the text that says how many friends you have online no longer moves to the bottom of the bar like the guild text does and just stays kinda off screen [like this](https://i.imgur.com/DBgs8Jg.png)

**Comment by Vicious-wow** [comment]
Thanks for the issue report. I haven't used the option to display the bar at the top so I didn't know about this. Will get on fixing it when I get up tomorrow.

**Comment by Vicious-wow** [comment]
Fixed. I've also added the ability to offset the social/guild online friends number in the options under Interface > AddOns > XIV Bar > Modules > Micromenu.
