### ISSUE TITLE
Micromenu is not showing guild members

### ISSUE THREAD

**Issue by RenatoDTH** [Vicious-wow/XIV_Databar#11]
First of all, thank you for updating the addon. You are  a true hero.

The Lua error is: '@XIV_Databar\modules\micromenu.lua"]:445: in function <XIV_Databar\modules\micromenu.lua:429'

Thanks

**Comment by Vicious-wow** [comment]
Hey, thanks for reporting the bug and I appreciate the compliment :)
I've re-installed wow entirely for the pre-patch in preparation for SL and have noticed this error too. Also another one - once I'm actually able to log in again (auth servers seem to be having problems) and fix this, I'll upload it right away.

**Comment by Vicious-wow** [comment]
Hm, I misread the title. I thought you meant the social tooltip.
Can you copy paste me the full error message, or is there no further information? I'm not receiving any errors when triggering the guild tooltip.

**Comment by RenatoDTH** [comment]
Actually its about social tooltip. 
The Lua error is only that line. Except if i misread something, since there are some lua errors from others addons.
Do not worry about the text, because i disabled to not show how many were on.

![error](https://user-images.githubusercontent.com/59841009/96019545-0c6c4b00-0e23-11eb-98a9-1d957e903284.PNG)

**Comment by Vicious-wow** [comment]
Weird. Line 445 for me is an if-check about whether you have social text or the social icon activated. Turning either of those settings on/off in any combination does not replicate the bug for me.
Try disabling all other addons and see if it still happens.

**Comment by RenatoDTH** [comment]
It worked! Its some conflict with a randon addon... Ty ver much and sorry to waste the time

**Comment by Vicious-wow** [comment]
It's all gucci friend.

**Comment by Bloomsalot** [comment]
So i recently came across this and a few other random errors that i cannot replicate, but this one i can, even after disabling addons. 
Here is the error message:
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:452: attempt to call global 'GetNumFriends' (a nil value)
Time: Tue Oct 27 20:14:26 2020
Count: 5
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:452: attempt to call global 'GetNumFriends' (a nil value)
[string "=[C]"]: in function `GetNumFriends'
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:452: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:429>
