### ISSUE TITLE
Error messages, all addons disabled

### ISSUE THREAD

**Issue by Bloomsalot** [Vicious-wow/XIV_Databar#13]
So here are the error messages im getting, I have turned off all of my addons just to see what was really happening. 

Error 1: 
Message: Interface\AddOns\XIV_Databar\modules\gold.lua:81: attempt to call field 'GetDate' (a nil value)
Time: Tue Oct 27 20:19:15 2020
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\gold.lua:81: attempt to call field 'GetDate' (a nil value)
[string "@Interface\AddOns\XIV_Databar\modules\gold.lua"]:81: in function <Interface\AddOns\XIV_Databar\modules\gold.lua:70>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:529: in function `InitializeAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:644: in function <...ddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

Error 2:
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:402: attempt to call global 'GetNumFriends' (a nil value)
Time: Tue Oct 27 20:19:15 2020
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:402: attempt to call global 'GetNumFriends' (a nil value)
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:402: in function `UpdateFriendText'
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:155: in function `Refresh'
[string "@Interface\AddOns\XIV_Databar\core.lua"]:317: in function `Refresh'
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:99: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:85>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:558: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:571: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:651: in function <...ddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:618: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1373: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>

Error 3:
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:402: attempt to call global 'GetNumFriends' (a nil value)
Time: Tue Oct 27 20:19:15 2020
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:402: attempt to call global 'GetNumFriends' (a nil value)
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:402: in function `UpdateFriendText'
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:155: in function `Refresh'
[string "@Interface\AddOns\XIV_Databar\core.lua"]:317: in function `Refresh'
[string "@Interface\AddOns\XIV_Databar\modules\armor.lua"]:37: in function <Interface\AddOns\XIV_Databar\modules\armor.lua:29>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:558: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:571: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:651: in function <...ddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:618: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1373: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>

Error 4: 
Message: Interface\AddOns\XIV_Databar\modules\currency.lua:143: attempt to call global 'GetCurrencyInfo' (a nil value)
Time: Tue Oct 27 20:19:15 2020
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\currency.lua:143: attempt to call global 'GetCurrencyInfo' (a nil value)
[string "@Interface\AddOns\XIV_Databar\modules\currency.lua"]:143: in function `StyleCurrencyFrame'
[string "@Interface\AddOns\XIV_Databar\modules\currency.lua"]:110: in function `Refresh'
[string "@Interface\AddOns\XIV_Databar\modules\currency.lua"]:42: in function <Interface\AddOns\XIV_Databar\modules\currency.lua:33>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:558: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:571: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:651: in function <...ddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:618: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1373: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>

Error 5:
Message: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:302: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: Tue Oct 27 20:19:15 2020
Count: 1
Stack: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:302: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua"]:302: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:298>
[string "@Interface\AddOns\XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua"]:317: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:314>
[string "@Interface\AddOns\XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua"]:550: in function `ForceUpdate'
[string "@Interface\AddOns\XIV_Databar\modules\talent.lua"]:68: in function <Interface\AddOns\XIV_Databar\modules\talent.lua:55>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:558: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:571: in function `EnableAddon'
[string "@Interface\AddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:651: in function <...ddOns\XIV_Databar\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:618: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1373: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>

Error 6:
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:388: attempt to call global 'GuildRoster' (a nil value)
Time: Tue Oct 27 20:19:19 2020
Count: 2
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:388: attempt to call global 'GuildRoster' (a nil value)
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:388: in function `UpdateGuildText'
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:369: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:368>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[string "=[C]"]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
[string "@Interface\AddOns\XIV_Databar\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:90: in function `Fire'
[string "@Interface\AddOns\XIV_Databar\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ddOns\XIV_Databar\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Error 7:
Message: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:302: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: Tue Oct 27 20:19:15 2020
Count: 1
Stack: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:302: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua"]:302: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:298>
[string "@Interface\AddOns\XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua"]:317: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:314>
[string "@Interface\AddOns\XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua"]:360: in function `?'
[string "@Interface\AddOns\XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua"]:65: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:65>

Locals: (*temporary) = nil

Im Sorry thats so much! I really love this addon, in fact its one of, it not my top favorite. Any help is appreciated. Thank you for keeping this going!

**Comment by Bloomsalot** [comment]
Nvm, it never updated when i got the new code /facepalm

**Comment by Vicious-wow** [comment]
I was just in the process of writing a reply - guess it resolved itself. All those bugs are deprecated API calls that have broken a few to a shit ton of lines in multiple modules over the 2 years or so of the addon not being updated. Those bugs should be gone with this github version, as well as some extra functionality and (imo) better looking tooltips. Let me know if anything else is wrong.

**Comment by Bloomsalot** [comment]
Nah man works great now that i updated it properly. 
Seriously a huge thank you for working on this you hate to see your favorite addons not being continued. I dont know what kinda help i can be other than suggestions or maybe a donation but id love to help
