### ISSUE TITLE
General Question on XIV_Databar

### ISSUE THREAD

**Issue by thomasthebear** [Vicious-wow/XIV_Databar#16]
Any reason as to why you're continuing to maintain XIV_Databar versus just utilizing the time to possibly just create a XIV_Databar "Theme Bundle", ie Make modules and adjustments that could be installed/utilized as additions to currently available & maintained LDB Databars (ChocolateBar, Titan Panel, etc)? My opinion, so take it as such, with you mentioning it's "borked" lol I feel like that may end up being an better route. Hopefully I'm conveying my point clear enough, a bit tired at time of writing this. I'd be more then willing to pitch into a project such as that if you decided upon that route or a similar one, though I don't have any previous work to show for it I can say I'm not completely incompetent.

**Comment by Vicious-wow** [comment]
Heya.
I said specifically the reputation (and azerite) bar was borked, not the entire addon. When I say something is badly coded, it doesn't mean it's unsalvageable, it just means it makes working with certain parts of the addon more difficult than it should be. If i started writing plugins for the databars you mentioned i would just as much (or more) have to fight with their established rules for making plugins work in their addons. That doesn't only take freedom away from me, but also means I will have to work with stupid things in their addons. You have no idea how many brain cells i've lost by dealing with ElvUI.

Fixing and maintaining this addon is just a project of mine that I do on the side while playing the game. Improving functionality, fixing bugs and re-writing badly performing code are all things that give me joy for some reason. And making people use a databar addon they don't like just to make it look like this one, while also being a performance nightmare to load an entire databar just to then change most of its looks and modules afterwards, is not really something i'd be happy with.
