### ISSUE TITLE
CurseBreaker support (packaged addon)

### ISSUE THREAD

**Issue by Kazlehoff** [Vicious-wow/XIV_Databar#19]
Any chance you can Package your releases with something like BigWigs Packager (https://github.com/BigWigsMods/packager) so the addon can be updated through addon managers, such as CurseBreaker?

thanks! :)

**Comment by Vicious-wow** [comment]
Hello. I did not know this existed. Will look at this whenever I have time and coffeine.

**Comment by Vicious-wow** [comment]
Don't really have an interest of setting this up. I plan to have this thing on curse by the time shadowlands comes out or shortly after anyway. Can just auto-update then.
