### ISSUE TITLE
Lua Errors in SL Beta

### ISSUE THREAD

**Issue by flow0284** [Vicious-wow/XIV_Databar#2]
```
1x ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-22.lua:302: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: ?
[string "@XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-22.lua"]:302: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:298>
[string "@XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-22.lua"]:317: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:314>
[string "@XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-22.lua"]:360: in function `?'
[string "@XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-22.lua"]:65: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:65>

Locals:
(*temporary) = nil
```

```
3x XIV_Databar\modules\micromenu.lua:408: attempt to index field 'guild' (a nil value)
[string "@XIV_Databar\modules\micromenu.lua"]:408: in function `UpdateGuildText'
[string "@XIV_Databar\modules\micromenu.lua"]:171: in function `Refresh'
[string "@XIV_Databar\core.lua"]:318: in function `Refresh'
[string "@XIV_Databar\modules\micromenu.lua"]:113: in function <XIV_Databar\modules\micromenu.lua:99>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua"]:527: in function `EnableAddon'
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua"]:540: in function `EnableAddon'
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua"]:620: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:493: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:616: in function `TimeManager_LoadUI'
[string "@FrameXML\UIParent.lua"]:1353: in function <FrameXML\UIParent.lua:1250>
```

**Comment by Vicious-wow** [comment]
I don't have access to beta and I've heard of other AddOns having issues because Blizzard has screwed up certain API calls on the PTR server.
Since I don't have beta I can't really do anything about this. If the cleaned up version I'll have prepared for when SL releases still throws these errors I'll take a look at it.

**Comment by Vicious-wow** [comment]
The second bug at the least is not related to the beta - I'll have that bug fixed with the next commit. It's caused when not having the guild module enabled + not being in a guild.

**Comment by Vicious-wow** [comment]
I've removed the entire code related to the first error you've received. This code created a frame for the legion artifact weapon and showed an AP bar. Since this code and thus the library that caused the error is no longer necessary I've removed it all. Was on my to-do list anyway, but now it's done.

I'm assuming the GetItemInfo() API got deleted or moved in Shadowlands, causing the error on PTR but not on live. Please let me know if you encounter any more bugs.

**Comment by flow0284** [comment]
Thx. So all modules on the right side like Gold are not working:

Gold:
```
1x XIV_Databar\modules\currency-Abzeichen.lua:307: attempt to call global 'GetCurrencyListSize' (a nil value)
[string "@XIV_Databar\modules\currency-Abzeichen.lua"]:307: in function <XIV_Databar\modules\currency.lua:303>
[string "=(tail call)"]: ?
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1235: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1144: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1648: in function `FeedGroup'
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@WeakAuras\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:526: in function `Select'
[string "@WeakAuras\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:534: in function `SelectByValue'
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1744: in function `FeedGroup'
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1928: in function `Open'
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1956: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1954>
[string "=[C]"]: ?
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0-41\widgets\AceGUIContainer-BlizOptionsGroup.lua"]:20: in function <...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19>
[string "=[C]"]: in function `Show'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:28: in function `InterfaceOptionsList_DisplayPanel'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
```

It looks like that C_CurrencyInfo is mandatory now

**Comment by Vicious-wow** [comment]
Ah, yea I was thinking that there must still be a bunch of deprecated API calls used in the AddOn. This is the first WoW AddOn i've picked up so i'm not aware of all the deprecated calls that don't give an error message yet. I'll go and use the newer call for that error in the modules affected. With the next commit it should work.

If you don't mind, keep posting the errors that pop up related to this. I don't have beta and it's much better to have the AddOn bug free when SL comes out so I can actually play the game :D

Thank you very much!

**Comment by Vicious-wow** [comment]
I have added the changes in the currency module. You can download the currency.lua file from the new "shadowlands" branch in this repository. Any shadowlands-specific changes that I can't yet implement on the live version of the addon, I will add there.

**Comment by flow0284** [comment]
So with your latest changes in the currency module. there are now lus errors with this module, but there is still nothing on the right side of the panel.

![grafik](https://user-images.githubusercontent.com/27314841/89949068-93385800-dc27-11ea-9c59-97c0d8be09d8.png)

**Comment by flow0284** [comment]
when i disable the elvui beta build the panel is working

**Comment by flow0284** [comment]
```
6x ElvUI\Core\Toolkit.lua:127: attempt to call method 'SetBackdrop' (a nil value)
[string "@ElvUI\Core\Toolkit.lua"]:127: in function `SetTemplate'
[string "@XIV_Databar\modules\talent.lua"]:21: in function `SkinFrame'
[string "@XIV_Databar\modules\talent.lua"]:333: in function `CreateSpecPopup'
[string "@XIV_Databar\modules\talent.lua"]:162: in function `CreateFrames'
[string "@XIV_Databar\modules\talent.lua"]:67: in function <XIV_Databar\modules\talent.lua:56>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua"]:527: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "@XIV_Databar\modules\talent.lua"]:503: in function <XIV_Databar\modules\talent.lua:500>
[string "=[C]"]: ?
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...bs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>
```

**Comment by Vicious-wow** [comment]
I loathe ElvUI. I hate it with an absolute passion. The amount of bugs related to ElvUI's shitty code and other addons trying to have ElvUI-skinning options or other ways to accommodate for it. Pure hatred.

I'll have a look at the beta build and their changes, I guess the SkinFrame function in some modules that get tooltip styling from ElvUI is broken.

**Comment by Vicious-wow** [comment]
Sorry for the late reply, whenever something involves ElvUI i just shut off and put it on the back back back burner of things I want to do.

I've located the issue: [https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrops](Backdrop API changes in Shadowlands)
This simply means I will have to opt into the backdrop API by declaring it in whichever frames I intend to it in. I'll update both the live and the beta branches with the updated code.

I hope this fixes that particular error. And thank you so much for helping - let me know of any additional errors that will certainly pop up after this.

**Comment by Amanthuul** [comment]
core.lua:358 needs to be changed to
local inOrderHall = C_Garrison.IsPlayerInGarrison(Enum.GarrisonType.Type_7_0);

or, since inOrderHall is not used anywhere, just delete it :)

**Comment by Vicious-wow** [comment]
Thanks for pointing that out! I completely forgot to look for orderhall related stuff in core.lua when i went through the files to remove code from outdated in-game systems. Out of curiosity, do you happen to know what this code was used for? The ability to hide and offsetting etc. only get triggered when the bar is on top and in OffsetUI() it does that API call without doing anything with it after. Super weird.

I'm deleting all of it, thank you for helping out.

**Comment by Amanthuul** [comment]
I don't know if it worked in past, but in Legion there was top bar in default interface while you are in Order Hall, i think it was attempt to handle it by moving whole bar a bit down.

**Comment by Amanthuul** [comment]
LibQTip still throwing errors when i hover mouse over Spec module and Guild button

1x XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua:442: attempt to call method 'SetBackdrop' (a nil value)
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:442: in function <XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0.lua:425>
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:729: in function `Clear'
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:384: in function <XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0.lua:352>
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:138: in function `Release'
[string "@XIV_Databar\modules\talent.lua"]:190: in function <XIV_Databar\modules\talent.lua:184>

Locals:
cell = <unnamed> {
 0 = <userdata>
 _paddingL = 0
 _provider = <table> {
 }
 g = 0.999998
 r = 0.999998
 b = 0.999998
 _paddingR = 0
 fontString = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 _paddingL = 0
 _provider = <table> {
 }
 g = 0.999998
 r = 0.999998
 b = 0.999998
 _paddingR = 0
 fontString = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
ClearFrameScripts = <function> defined @XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0.lua:1283

**Comment by Vicious-wow** [comment]
Yea i'm retarded and only added backdrop functionality for the tooltips, not the cells. This LibQTip-1.0 version should have it fixed. Thank you.

**Comment by Amanthuul** [comment]
and yet,

```
11x XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua:171: attempt to call method 'SetBackdrop' (a nil value)
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:171: in function <XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0.lua:167>
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:735: in function `Clear'
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:384: in function <XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0.lua:352>
[string "@XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0-44.lua"]:138: in function `Release'
[string "@XIV_Databar\modules\talent.lua"]:190: in function <XIV_Databar\modules\talent.lua:184>

Locals:
frame = BackdropTemplate {
 0 = <userdata>
 height = 13.852776
}
(*temporary) = nil
(*temporary) = BackdropTemplate {
 0 = <userdata>
 height = 13.852776
}
(*temporary) = nil
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
ClearFrameScripts = <function> defined @XIV_Databar\Libs\LibQTip-1.0\LibQTip-1.0.lua:1283
tinsert = <function> defined =[C]:-1
frameHeap = <table> {
}
```

Just commenting libQTip:171 worked w/o any glitches.

**Comment by Vicious-wow** [comment]
lmao, this is persistent and i'm a potato. Can you take the newest LibQTip-1.0.lua in the shadowlands branch and see if the bug still occurs now? Thank you for the help.

**Comment by Amanthuul** [comment]
Yup, it worked.
