### ISSUE TITLE
GuildHoverTooltip is cutting names

### ISSUE THREAD

**Issue by Duff166** [Vicious-wow/XIV_Databar#21]
If I hover over the Crown/Guild the names of a few people are cutted. The first two letters are missing.
I use the newest version.

2x XIV_Databar\modules\micromenu.lua:546: attempt to index field '?' (a nil value)
[string "@XIV_Databar\modules\micromenu.lua"]:546: in function <XIV_Databar\modules\micromenu.lua:483>

Locals:
modifierFunc = <function> defined =[C]:-1
tooltip = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 headerFont = GameTooltipHeaderText {
 }
 backdropInfo = <table> {
 }
 scripts = <table> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
 height = 154.183936
 columns = <table> {
 }
 cell_margin_v = 3
 TopEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 regularFont = GameTooltipText {
 }
 width = 389.967331
 cell_margin_h = 6
 colspans = <table> {
 }
 labelProvider = <table> {
 }
 key = "SocialToolTip"
 BottomRightCorner = <unnamed> {
 }
 scrollChild = <unnamed> {
 }
 LeftEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
}
_ = 57
totalBNOnlineFriends = 30
totalOnlineFriends = 0
playerFaction = "Horde"
r = 0.999998
g = 0.999998
b = 0.999998
(for index) = 7
(for limit) = 57
(for step) = 1
i = 7
friendAccInfo = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "|Kq19|k"
 battleTag = "Kirito#24100"
 note = ""
 rafLinkType = 0
 bnetAccountID = 55
 appearOffline = false
 customMessage = "BMTH - Kingslayer"
 lastOnlineTime = 1605300482
 customMessageTime = 1605113880
 isAFK = false
 isBattleTagFriend = true
}
gameAccount = <table> {
 isGameAFK = false
 clientProgram = "ZEUS"
 richPresence = "Playing Zombies on Die Maschine"
 isGameBusy = false
 gameAccountID = 81
 isWowMobile = false
 hasFocus = true
 canSummon = false
 isOnline = true
}
charName = nil
gameClient = "ZEUS"
realmName = nil
faction = nil
zone = nil
richPresence = "Playing Zombies on Die Maschine"
isWoW = false
isClassic = false
statusIcon = "FriendsFrame\StatusIcon-Online"
socialIcon = "FriendsFrame\Battlenet-CallOfDutyBlackOpsColdWaricon"
(*temporary) = nil
(*temporary) = "FriendsFrame\Battlenet-CallOfDutyBlackOpsColdWaricon"
(*temporary) = ""
(*temporary) = <table> {
 1 = "WoW"
 2 = "S2"
 3 = "D3"
 4 = "WTCG"
 5 = "Hero"
 6 = "Pro"
 7 = "S1"
 8 = "DST2"
 9 = "VIPR"
 10 = "ODIN"
 11 = "LAZR"
 12 = "W3"
}
(*temporary) = "|TFriendsFrame\StatusIcon-Online:16|t|cff82c5ff |Kq28|k|r "
(*temporary) = "WoW Classic - Firemaw |TFriendsFrame\Battlenet-WoWicon:16|t"
(*temporary) = <function> defined @Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0.lua:1420
(*temporary) = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 headerFont = GameTooltipHeaderText {
 }
 backdropInfo = <table> {
 }
 scripts = <table> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
 height = 154.183936
 columns = <table> {
 }
 cell_margin_v = 3
 TopEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 regularFont = GameTooltipText {
 }
 width = 389.967331
 cell_margin_h = 6
 colspans = <table> {
 }
 labelProvider = <table> {
 }
 key = "SocialToolTip"
 BottomRightCorner = <unnamed> {
 }
 scrollChild = <unnamed> {
 }
 LeftEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
}
(*temporary) = 8
(*temporary) = "OnMouseUp"
(*temporary) = <function> defined @XIV_Databar\modules\micromenu.lua:610
(*temporary) = nil
(*temporary) = <function> defined @Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0.lua:1366
(*temporary) = <unnamed> {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 _OnMouseUp_func = <function> defined @XIV_Databar\modules\micromenu.lua:610
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 _OnEnter_func = <function> defined @XIV

**Comment by Vicious-wow** [comment]
Hey.
You say the issue is cut-off names in the guild tooltip, but the error message is entirely related to the social tooltip. Which names are cut-off? What settings do you have in your micromenu options? Does the bug happen with all other addons disabled?

**Comment by Duff166** [comment]
Just names with accents like ´ ` ^ and so on are cutted. You can see it on the screenshot. Top is with all addons loaded, bottom with just XIV-Databar loaded - no difference.
Original Names are:
Dîras, Éisenschild and Gorèdusthoof. So every letter until the special and inclusive the "special" letter are gone.

In the micromenu settings just "Hide Social Text" is disabled, everything else is enabled.
My game language is english.

And Iam sorry! Found out that the error message is related to the social tooltip which is not loading/showing. The guild tooltip is just cutting names with no error message.
![XIV DataBar](https://user-images.githubusercontent.com/71339202/99148371-8ba1a880-2687-11eb-808d-892e040d065d.png)

**Comment by Vicious-wow** [comment]
Newest version should have the fix for the cut-off names in the guild tooltip. The error you received from the social tooltip is related to, what I interpret the error message as, a friend of yours playing a game that is not accounted for in the AddOn. The gameClient is "ZEUS2". If you let me know what he was playing I can add it so it doesn't happen again.

**Comment by Duff166** [comment]
Cut-off names are fixed. Thank you very much!
The error message has to be related to the new Call of Duty: Black Ops Cold War. Google is also giving me the information that "Zeus" is a codename for that game.

**Comment by Vicious-wow** [comment]
I've added the new game, so the social tooltip shouldn't blow up anymore when someone on your friendlist plays it.
