### ISSUE TITLE
Friends on Hover broke in a update

### ISSUE THREAD

**Issue by TheCynicalKitty** [Vicious-wow/XIV_Databar#23]
Friends on hover broken in one of ya updates :) as shown here
https://thecynicalkitty.com/s/20201417907.mp4

**Comment by Vicious-wow** [comment]
Hey. Doesn't happen for me. Unless this can be replicated in a consistent way or throws an error message I won't touch it. Will keep this thread alive for more scenarios in which it might or might not happen.
