### ISSUE TITLE
Social tool tip

### ISSUE THREAD

**Issue by Bloomsalot** [Vicious-wow/XIV_Databar#24]
Getting this error whenever i hover over the social button

Message: table index is nil
Time: Fri Nov 27 20:37:50 2020
Count: 2
Stack: table index is nil
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua"]:30: in function <...AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:572: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:486>

**Comment by Vicious-wow** [comment]
Disable "AddOnSkins" and see if it still happens. It looks like that addon is causing the error.

**Comment by Bloomsalot** [comment]
So i updated XIV last night but was still getting the error, even after disabling ADDONSKINS, and was still getting the error, load in today and now im not recieving the error, with or without Addonskins....weird

**Comment by Bloomsalot** [comment]
disabled Addonskins got this error

Message: table index is nil
Time: Sat Nov 28 14:21:24 2020
Count: 1
Stack: table index is nil
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\AceLocale-3.0\AceLocale-3.0.lua"]:30: in function <...ddOns\DataStore\libs\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:572: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:486>

disabled datastore got
Message: table index is nil
Time: Sat Nov 28 14:22:37 2020
Count: 1
Stack: table index is nil
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\Details\Libs\AceLocale-3.0\AceLocale-3.0.lua"]:30: in function <...\AddOns\Details\Libs\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:572: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:486>

**Comment by Bloomsalot** [comment]
followed through with like 6 other addons, disabling them one by one, finally got back to this 

Message: table index is nil
Time: Sat Nov 28 14:26:38 2020
Count: 1
Stack: table index is nil
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\XIV_Databar\Libs\AceLocale-3.0\AceLocale-3.0.lua"]:30: in function <...Ons\XIV_Databar\Libs\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:572: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:486>

**Comment by Vicious-wow** [comment]
This error seems to have something to do when one of your friends is playing on the opposite faction.
What language is your game client? Are you playing on Alliance or Horde?

**Comment by Bloomsalot** [comment]
Alliance, english

**Comment by Vicious-wow** [comment]
I'm also playing on the english client, and if I log into an alliance character I don't get an error message for the friends who play on Horde.
Navigate to: C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\XIV_Databar\modules
Open micromenu.lua, insert the following 2 lines between line 571 and 572 (so 571 is 571 and 572 is now line 574):

`print('Character: ' .. charName)`
`print('Faction: ' .. L[faction])`

Line 571 is `local factionColors = { ['Alliance'] = "ff008ee8", ['Horde'] = "ffc80000" }` in case you have a text editor that doesn't display lines of code, search it out via CTRL+F.

When you now hover over the social tooltip, what what's getting printed to the chat?

**Comment by Bloomsalot** [comment]
[06:16] Character: Dwärfy 
[06:16] Faction: Horde 
[06:16] Character:

**Comment by Vicious-wow** [comment]
Well, open the blizzard friendslist and see which friend is causing the empty character.

**Comment by Bloomsalot** [comment]
then what?

**Comment by Vicious-wow** [comment]
So I know that maybe some weird character name is making the charname return nothing. Maybe the character is actually Alliance even though it should be Horde. Maybe maybe a crap ton of things. If you don't provide me with information I can't help you.

**Comment by Bloomsalot** [comment]
seems like its a blizzard thing, this isnt the first bug ive seen with characters today, in guild someone was talking but i could only see what they were saying in the guild tab, not in guild chat, and their name wasnt showing.
and i can see a person playing that is just a blank name, but i hover over them and says their characters name

**Comment by Bloomsalot** [comment]
character is Alegadom-Ragnaros

**Comment by Vicious-wow** [comment]
I've seen this bug happen with chinese players submitting issues here. Very weird, I didn't know this happened to some people in the western game clients as well. Can you swap the 2 prints, so faction is first and then character name? I wanna know if faction is also nil and not just char name. I have a check in the code to just display "No Info" if a character name couldn't be retrieved. If faction is also nil that's probably what's causing the error here.

**Comment by Bloomsalot** [comment]
[07:01] Faction: Horde 
[07:01] Character: Dwärfy
thats all that printed

**Comment by Vicious-wow** [comment]
I'm going to bed now, but I'm pretty sure the faction being nil is what's causing this. No idea why the blizzard call is borked in so many different functions and just leaves you with no information about people on your friendslist. I've had reports about this since pre-patch, so i'm guessing SL screwed with this and it'll take them 50 years to address it.

I'll add a (hopefully working) fix for this tomorrow when I get up.

**Comment by Bloomsalot** [comment]
Thanks Man

**Comment by Vicious-wow** [comment]
I hope that fixes it. It should now properly catch character information being nil from blizzard and replace it with placeholder text. Reopen this issue if there's still fucky things happening.

**Comment by Bloomsalot** [comment]
thanks, i havent installed it yet but the issue has seemed to fix itself, the one friend i had not showing up is now showing up and not causing the error, Thank you for the quick responses! Seriously do love this addon and its become a part of my ui that iu feel naked without it
