### ISSUE TITLE
Question: How to move the databar

### ISSUE THREAD

**Issue by IWasABook** [Vicious-wow/XIV_Databar#25]
Hello, by default the databar is at the bottom of my screen. Is there a way to move it all the way to the top? Right now it overlaps with my chat and my ability bars. I could move the chat and bars but I would prefer to have the databar on the top of my screen.

**Comment by Vicious-wow** [comment]
Press ESC --> Interface --> AddOns --> Left-Click "XIV Bar" -> Bar Position "Top"
