### ISSUE TITLE
Can't install via WoWUp

### ISSUE THREAD

**Issue by filliph** [Vicious-wow/XIV_Databar#27]
It looks like this repository doesn't have any releases built, so when attempting to install this via WoWUp I get the following message:

![image](https://user-images.githubusercontent.com/9424286/101367104-adb0d400-389d-11eb-96f5-657fd06f5fbd.png)

Could you please generate releases for your existing tags so it's possible to install this add-on? Thanks!

**Comment by Vicious-wow** [comment]
Sure why not.
