### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by Freeruns** [Vicious-wow/XIV_Databar#32]
1x [ADDON_ACTION_BLOCKED] Модификация 'XIV_Databar' пыталась вызвать защищенную функцию 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:305: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:244>
[string "=[C]"]: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:181: in function `OnTargetChanged'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:61: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

**Comment by Vicious-wow** [comment]
This bug doesn't have anything to do with this addon. Not sure why it says XIV_Databar is responsible for this bug, but there's not a single "SetTargetClampingInsets()" function used in the entire addon. Also, the addon doesn't do anything with nameplates.
