### ISSUE TITLE
(Request) Customized Hearthstone?

### ISSUE THREAD

**Issue by lubitow** [Vicious-wow/XIV_Databar#33]
Currently, you only have the option to set one hearth on the bar to say "Dalaran/Garrison/Etc" and "Main" but would it be possible to add functionally to use one of the "toy" hearthstones that changes the appearance of your main hearthstone? Or similar to druids if you are on a mage you can set it to portal/teleport to a known location?

**Comment by Vicious-wow** [comment]
This and other things are on the to-do list and will be worked on whenever i'm not playing the game as much.
