### ISSUE TITLE
LUA error when mouseover on Social

### ISSUE THREAD

**Issue by randompsique** [Vicious-wow/XIV_Databar#36]
Hi!

Since yesterday I started getting this LUA error when doing mouseover on the social icon:

Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:607: bad argument #3 to 'format' (string expected, got nil)
Time: Wed Jan 27 16:51:18 2021
Count: 7
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:607: bad argument #3 to 'format' (string expected, got nil)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:607: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:486>

Locals: errMsg = "Interface\AddOns\XIV_Databar\modules\micromenu.lua:607: bad argument #3 to 'format' (string expected, got nil)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

Not sure what could it be triggering it. It happens constantly. Thanks!

**Comment by Vicious-wow** [comment]
Someone in your friend list must be playing a game that is not added to the addon yet. A wild guess is they released another Call of Duty? Tell me which games your friends are playing when you try to mouse over the social icon.

**Comment by Vicious-wow** [comment]
Since there's no reply i'm assuming the issue has fixed itself. Either way if you don't wanna have this fixed there's nothing for me to do.
