### ISSUE TITLE
Friend List No longer working

### ISSUE THREAD

**Issue by FastlaneHS** [Vicious-wow/XIV_Databar#37]
There was a small update to my wow client today.  The friend list no longer shows anything when hovering over the icon.  The following is the error I recieve:
`13x table index is nil
[string "=[C]"]: ?
[string "@AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0-6.lua"]:30: in function <...AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@XIV_Databar\modules\micromenu.lua"]:572: in function <XIV_Databar\modules\micromenu.lua:486>

Locals:
(*temporary) = <table> {
 Show PVP Button = "Show PVP Button"
 Session Total = "Session Total"
 Right = "Right"
 Second Currency = "Second Currency"
 Cleaned = "Cleaned"
 k = "k"
 Bar Padding = "Bar Padding"
 Change Port Option = "Change Port Option"
 Realm Time = "Realm Time"
 Horizontal Position = "Horizontal Position"
 Artifact Knowledge = "Artifact Knowledge"
 Normal = "Normal"
 Available Ranks = "Available Ranks"
 Remaining = "Remaining"
 Bottom = "Bottom"
 Classic = "Classic"
 Whisper BNet = "Whisper BNet"
 Set Loot Specialization = "Set Loot Specialization"
 Talent Minimum Width = "Talent Minimum Width"
 Top = "Top"
 Show Help Button = "Show Help Button"
 Bar Width = "Bar Width"
 Show Pets Button = "Show Pets Button"
 Use Server Time = "Use Server Time"
 Current Loot Specialization = "Current Loot Specialization"
 Hide Event Text = "Hide Event Text"
 Show Social Tooltips = "Show Social Tooltips"
 Alliance = "Alliance"
 Right-Click = "Right-Click"
 Show Shop Button = "Show Shop Button"
 Open Artifact = "Open Artifact"
 Only the alpha can be set with the color picker = "Only the alpha can be set with the color picker"
 Main Menu Icon Right Spacing = "Main Menu Icon Right Spacing"
 Hide BNet App Friends = "Hide BNet App Friends"
 Set Specialization = "Set Specialization"
 No Tag = "No Tag"
 Hide Social Text = "Hide Social Text"
 Master Volume = "Master Volume"
 Show Tooltips = "Show Tooltips"
 Show All Addons in Tooltip with Shift = "Show All Addons in Tooltip with Shift"
 Cooldowns = "Cooldowns"
 Whisper Character = "Whisper Character"
 Ready = "Ready"
 Show Quests Button = "Show Quests Button"
 Hide Bar in combat = "Hide Bar in combat"
 No Info = "No Info"
 Durability Warning Threshold = "Durability Warning Threshold"
 Use Class Colors for XP Bar = "Use Class Colors for XP Bar"
 Use Class Colors = "Use Class Colors"
 New Event! = "New Event!"
 Bar Position = "Bar Position"
 Garbage Collect = "Garbage Collect"
 Font = "Font"
 Module Spacing = "Module Spacing"
 Memory Usage = "Memory Usage"
 Show Chat Button = "Show Chat Button"
 Gold rounded values = "Gold rounded values"
 Toggle Profession Frame = "Toggle Profession Frame"
 Use Class Color for Bar = "Use Class Color for Bar"
 Addons to Show in Tooltip = "Addons to Show in Tooltip"
 Number of Addons To Show = "Number of Addons To Show"
 GMOTD in Tooltip = "GMOTD in Tooltip"
 Show World Ping = "Show World Ping"
 Open Clock = "Open Clock"
 Show Achievements Button = "Show Achievements Button"
 Show Social Button = "Show Social Button"
 Use Class Color for Text = "Use Class Color for Text"
 Text Style = "Text Style"
 Bar Color = "Bar Color"
 Show Journal Button = "Show Journal Button"
 Third Currency = "Third Currency"
 Icon Spacing = "Icon Spacing"
 First Currency = "First Currency"
 Port Options = "Port Options"
 Social Text Offset = "Social Text Offset"
 Hover = "Hover"
 Currency Select = "Currency Select"
 Current Specialization = "Current Specialization"
 Toggle Profession Spellbook = "Toggle Profession Spellbook"
 Show XP Bar Below Max Level = "Show XP Bar Below Max Level"
 Modifier for friend invite = "Modifier for friend invite"
 Travel = "Travel"
 Toggle Bags = "Toggle Bags"
 Show Talents Button = "Show Talents Button"
 Shorten Gold = "Shorten Gold"
 Colors = "Colors"
 Always Show Silver and Copper = "Always Show Silver and Copper"
 Horde = "Horde"
 Travel Cooldowns = "Travel Cooldowns"
 Open Calendar = "Open Calendar"
 Local Time = "Local Time"
 Time Format = "Time Format"
 Volume step = "Volume step"
 Open Guild Page = "Open Guild Page"
 B = "B"
 Show Coordinates = "Show Coordinates"
 Show Item Level = "Show Item Level"
 Text on Right = "Text on Right"
 Show Menu Button = "Show Menu Button"
 Modules = "Modules"
 Show LFG Button = "Show LFG Button"
 Center = "Center"
 Left = "Left"
 M = "M"
 L = "L"
 Inactive = "Inactive"
 Show Spellbook Button = "Show Spellbook Button"
 Use ElvUI for tooltips = "Use ElvUI for tooltips"
 Small Font Size = "Small Font Size"
 Left-Click = "Left-Click"
 Show Character Button = "Show Character Button"
 Show Guild Button = "Show `

**Comment by Vicious-wow** [comment]
Turn off all other AddOns, see if it still happens. If it does, can you send me the full error message? It looks cutoff at the start, not actually saying in which line the error appears. Are your friends online and playing certain games when this happens?

**Comment by Vicious-wow** [comment]
No reply means I can't help. Closing this.
