### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Izzystar** [Vicious-wow/XIV_Databar#9]
Shadowlands Beta 9.0.2

Message: Interface\AddOns\XIV_Databar\modules\gold.lua:81: attempt to call field 'GetDate' (a nil value)
Time: Mon Oct  5 11:48:29 2020
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\gold.lua:81: attempt to call field 'GetDate' (a nil value)
[string "@Interface\AddOns\XIV_Databar\modules\gold.lua"]:81: in function <Interface\AddOns\XIV_Databar\modules\gold.lua:70>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by Vicious-wow** [comment]
Thank you for reporting the bug.
I've updated the deprecated API call with the currently correct one. If you find any more bugs on the beta, you can just keep posting in this thread and i'll get on it.
